config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to:'users#my_portfolio'
  resources :investimentos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/investimento.rb
class Investimento < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates :price, presence: true
  validates :nivel, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user! 
end

app/controllers/investimentos_controller.rb
class InvestimentosController < ApplicationController
  before_action :set_investimento, only: [:edit, :update, :show, :destroy]
  
  def index
    @investimentos = Investimento.all
  end
  
  def new
    @investimento = Investimento.new
  end
  
  def create
    @investimento = Investimento.new(investimento_params)
    if @investimento.price < 500
      @investimento.nivel = 1
      @investimento.gain = @investimento.price * 0.05
    elsif @investimento.price >= 500 && @investimento.price < 1000
      @investimento.nivel = 2
      @investimento.gain = @investimento.price * 0.10
    elsif @investimento.price >= 1000 && @investimento.price <= 5000
      @investimento.nivel = 3
      @investimento.gain = @investimento.price * 0.15
    end
    
    if @investimento.save
      flash[:notice] = "Seu investimento foi recebido! Agradecemos a confiança."
      redirect_to investimento_path(@investimento)
    else
      render 'new'
    end
  end
  
  def show

  end
  
  def edit

  end
  
  def update

    if @investimento.update(investimento_params)
      flash[:notice] = "Investimento atualizado"
      redirect_to investimento_path(@investimento)
    else
      render 'edit'
    end
  end
  
  def destroy
    
    @investimento.destroy
    flash[:notice] = "A exclusão do investimento foi sucedida"
    redirect_to investimentos_path
  end
  
  private
    def set_investimento
      @investimento = Investimento.find(params[:id])
    end
    def investimento_params
      params.require(:investimento).permit(:name, :price)
    end
    
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/investimentos/edit.html.erb
<h1>Atualizar dados do investimento: <%= @investimento.name %></h1>

<% if @investimento.errors.any? %>
  <h3>Os seguintes erros foram encontrados:</h3>
  <ul>
      <% @investimento.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
  </ul>
<% end %>

<hr>
<%= form_for @investimento do |f| %>

<h4>Dados:</h4><br/>
<p><%= f.label :name %>: <%= f.text_field :name %> </p>
<p>Valor(R$): <%= number_to_currency(@investimento.price) %></p>
<p>Lucro(%): <% if @investimento.nivel == 1 %>
  5%
  <% elsif @investimento.nivel == 2 %>
  10%
  <% elsif @investimento.nivel == 3 %>
  15%
  <% end %>
</p>
<p>Lucro(R$): <%= number_to_currency(@investimento.gain) %></p>
<p>Recebido em: <%= @investimento.created_at.to_date %></p>
<p>Retirada (30 dias após o recebimento): <%= @investimento.dataretirada.to_date %></p>
<p><%= f.submit %></p>
<% end %>
<%= link_to "Voltar para investimentos", investimentos_path %>

app/views/investimentos/index.html.erb
<h1>Listando todos investimentos</h1>
<hr>

<table>
    <tr>
        <th>Nome</th>
        <th>Valor(R$)</th>
        <th>Lucro(%)</th>
        <th>Lucro(R$)</th>
        <th>Recebimento</th>
        <th>Retirada</th>
    </tr>
    
    <% @investimentos.each do |investimento| %>
    <tr>
        <td><%= investimento.name %></td>
        <td><%= number_to_currency(investimento.price) %></td>
        <td>
          <% if investimento.nivel == 1 %>
            5%
          <% elsif investimento.nivel == 2 %>
            10%
          <% elsif investimento.nivel == 3 %>
            15%
          <% end %>
        </td>
        <td><%= number_to_currency(investimento.gain) %></td>
        <td><%= investimento.created_at.to_date %></td>
        <td><%= investimento.dataretirada.to_date %></td>
        <td><%= link_to 'Editar', edit_investimento_path(investimento) %></td>
        <td><%= link_to 'Mostrar', investimento_path(investimento) %></td>
        <td><%= link_to 'Excluir', investimento_path(investimento), method: :delete, data: {confirm: "Tem certeza que deseja realizar a exclusão?"} %></td>
    </tr>
    <% end %>
</table>
<br>
<%= link_to 'Novo investimento', new_investimento_path %>

app/views/investimentos/new.html.erb
<h1>Formulário de Investimento:</h1>

<hr>

<% if @investimento.errors.any? %>
  <h3>Os seguintes erros foram encontrados:</h3>
  <ul>
    <% @investimento.errors.full_messages.each do |msg| %>
      <li>
        <% if msg == "Nivel can't be blank" %>
          <p>Valor investido não compatível.</p>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= form_for @investimento do |f| %>
<p>
<%= f.label :name %>(R$) (Título para melhor memorização)<br/>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :price %> (máx: R$5000,00)<br/>
<%= f.number_field :price %><br/>
R$ 0~500 > 5% lucro<br/> 
R$ 500~1000 > 10% lucro<br/> 
acima de R$ 1000 > 15% de lucro<br/> 
</p><br/>
<p>
<%= f.submit %>
</p>
<% end %>
<%= link_to "Voltar para investimentos", investimentos_path %>

app/views/investimentos/show.html.erb
<h1>Investimento: <%= @investimento.name.capitalize %></h1>
<hr>

<h4>Dados:</h4>
<p>Valor(R$): <%= number_to_currency(@investimento.price) %></p>
<p>Lucro(%): <% if @investimento.nivel == 1 %>
  5%
  <% elsif @investimento.nivel == 2 %>
  10%
  <% elsif @investimento.nivel == 3 %>
  15%
  <% end %>
</p>
<p>Lucro(R$): <%= number_to_currency(@investimento.gain) %></p>
<p>Recebido em: <%= @investimento.created_at.to_date %></p>
<%  @investimento.dataretirada = @investimento.created_at.to_date + 30 %>
<%  @investimento.save %>
<p>Retirada (30 dias após o recebimento): <%= @investimento.dataretirada.to_date %></p>
<%= link_to "Editar", edit_investimento_path(@investimento) %> |
<%= link_to "Voltar", investimentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MaxinApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MaxinApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          
          <%= yield %>
        </div>
      </div><!--/row-->
      <br>
      <hr>

      <footer>
        <p>&copy; Maxin 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/my_portfolio.html.erb
<h1>Investimentos</h1>

app/views/welcome/index.html.erb
<h1>Welcome to MAXIN</h1>

<%= link_to "MAXIN", investimentos_path %>

<%= link_to "logout", destroy_user_session_path, method: :delete %>